SC-4124: Upgrading PHP and extensions in all images. Adding additional Alpine images.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -134,6 +134,9 @@ script:
         echo "";
         pear list -c pecl
     '
+  - >
+    iconv_test=$(docker run -t --rm spryker/php:${SPRYKER_TAG} sh -c 'php -r "echo iconv(\"UTF-8\", \"ASCII//TRANSLIT\", \"español\");"');
+    if [ -n "$iconv_test" ]; then echo $iconv_test; else echo 'ICONV test is FAILED.' $iconv_test; exit 1; fi
   - docker images spryker/php
 
 notifications:
